### ISSUE TITLE
Not work with different model

### ISSUE THREAD

**Issue by korabelnikov** [msqr1/Vosklet#2]
On the step of model's creation (malloc) JS throw error without text but with 1 number, it looks like number of bytes tried to allocate.

Have you built model with fixed memory size? doesn't it allow memory_grow?

**Comment by msqr1** [comment]
I tried not to set ALLOW_MEMORY_GROWTH with pthread because I do lots of JS read and writes. See
 https://emscripten.org/docs/porting/pthreads.html?#special-considerations

last section about pthread and allow memory growth

**Comment by korabelnikov** [comment]
@msqr1 I tried to rebuild using your make script, I've set 600mb instead of 300, but error persist

model, I used from vosk-browser

https://github.com/ccoreilly/vosk-browser/raw/gh-pages/models/vosk-model-small-ru-0.4.tar.gz

**Comment by korabelnikov** [comment]
![image](https://github.com/msqr1/Vosklet/assets/3808833/f07cc3a8-412a-4739-872f-efaa86cca7c1)

the execution steps after model creation but then I got error with pointer to std::string (I suppose)

**Comment by msqr1** [comment]
Without getting my hand dirty, I can't know what is going on. I will try to build it with o0 later tonight.

**Comment by korabelnikov** [comment]
good, idea, I'll try it right now

**Comment by korabelnikov** [comment]
```
Vosklet.js:418 Aborted(native code called abort())
threadPrintErr @ Vosklet.js:418
abort @ Vosklet.js:903
__abort_js @ Vosklet.js:1959
$abort @ Vosklet.wasm-01f04bca:0x2b12f
$std::__2::__throw_out_of_range[abi:nn180100](char const*) @ Vosklet.wasm-01f04bca:0x2cefbb
$std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>::__throw_out_of_range[abi:nn180100]() const @ Vosklet.wasm-01f04bca:0x2cefb1
$std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>::basic_string(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>> const&, unsigned long, unsigned long, std::__2::allocator<char> const&) @ Vosklet.wasm-01f04bca:0x18069
$std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>::substr[abi:ne180100](unsigned long, unsigned long) const @ Vosklet.wasm-01f04bca:0x16eda
$genericModel::extractAndLoad(int, int)::$_0::operator()() const @ Vosklet.wasm-01f04bca:0x1590e
$decltype(std::declval<genericModel::extractAndLoad(int, int)::$_0&>()()) std::__2::__invoke[abi:ne180100]<genericModel::extractAndLoad(int, int)::$_0&>(genericModel::extractAndLoad(int, int)::$_0&) @ Vosklet.wasm-01f04bca:0x157d4
$void std::__2::__invoke_void_return_wrapper<void, true>::__call[abi:ne180100]<genericModel::extractAndLoad(int, int)::$_0&>(genericModel::extractAndLoad(int, int)::$_0&) @ Vosklet.wasm-01f04bca:0x15787
$std::__2::__function::__alloc_func<genericModel::extractAndLoad(int, int)::$_0, std::__2::allocator<genericModel::extractAndLoad(int, int)::$_0>, void ()>::operator()[abi:ne180100]() @ Vosklet.wasm-01f04bca:0x15612
$std::__2::__function::__func<genericModel::extractAndLoad(int, int)::$_0, std::__2::allocator<genericModel::extractAndLoad(int, int)::$_0>, void ()>::operator()() @ Vosklet.wasm-01f04bca:0x155d9
$std::__2::__function::__value_func<void ()>::operator()[abi:ne180100]() const @ Vosklet.wasm-01f04bca:0x1387d
$std::__2::function<void ()>::operator()() const @ Vosklet.wasm-01f04bca:0x137d5
$genericModel::extractAndLoad(int, int)::$_1::operator()() const @ Vosklet.wasm-01f04bca:0x13787
$decltype(std::declval<genericModel::extractAndLoad(int, int)::$_1>()()) std::__2::__invoke[abi:ne180100]<genericModel::extractAndLoad(int, int)::$_1>(genericModel::extractAndLoad(int, int)::$_1&&) @ Vosklet.wasm-01f04bca:0x13732
$void std::__2::__thread_execute[abi:ne180100]<std::__2::unique_ptr<std::__2::__thread_struct, std::__2::default_delete<std::__2::__thread_struct>>, genericModel::extractAndLoad(int, int)::$_1>(std::__2::tuple<std::__2::unique_ptr<std::__2::__thread_struct, std::__2::default_delete<std::__2::__thread_struct>>, genericModel::extractAndLoad(int, int)::$_1>&, std::__2::__tuple_indices<...>) @ Vosklet.wasm-01f04bca:0x12f77
$void* std::__2::__thread_proxy[abi:ne180100]<std::__2::tuple<std::__2::unique_ptr<std::__2::__thread_struct, std::__2::default_delete<std::__2::__thread_struct>>, genericModel::extractAndLoad(int, int)::$_1>>(void*) @ Vosklet.wasm-01f04bca:0x12b03
invokeEntryPoint @ Vosklet.js:1743
handleMessage @ Vosklet.js:516
Vosklet.js:418 worker: onmessage() captured an uncaught exception: RuntimeError: Aborted(native code called abort())
threadPrintErr @ Vosklet.js:418
handleMessage @ Vosklet.js:543
Vosklet.js:418 RuntimeError: Aborted(native code called abort())
    at abort (http://127.0.0.1:5000/static/Vosklet.js:922:11)
    at __abort_js (http://127.0.0.1:5000/static/Vosklet.js:1959:7)
    at Vosklet.wasm.abort (wasm://wasm/Vosklet.wasm-01f04bca:wasm-function[1146]:0x2b12f)
    at Vosklet.wasm.std::__2::__throw_out_of_range[abi:nn180100](char const*) (wasm://wasm/Vosklet.wasm-01f04bca:wasm-function[7047]:0x2cefbb)
    at Vosklet.wasm.std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>::__throw_out_of_range[abi:nn180100]() const (wasm://wasm/Vosklet.wasm-01f04bca:wasm-function[7046]:0x2cefb1)
    at Vosklet.wasm.std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>::basic_string(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>> const&, unsigned long, unsigned long, std::__2::allocator<char> const&) (wasm://wasm/Vosklet.wasm-01f04bca:wasm-function[449]:0x18069)
    at Vosklet.wasm.std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>::substr[abi:ne180100](unsigned long, unsigned long) const (wasm://wasm/Vosklet.wasm-01f04bca:wasm-function[422]:0x16eda)
    at Vosklet.wasm.genericModel::extractAndLoad(int, int)::$_0::operator()() const (wasm://wasm/Vosklet.wasm-01f04bca:wasm-function[411]:0x1590e)
    at Vosklet.wasm.decltype(std::declval<genericModel::extractAndLoad(int, int)::$_0&>()()) std::__2::__invoke[abi:ne180100]<genericModel::extractAndLoad(int, int)::$_0&>(genericModel::extractAndLoad(int, int)::$_0&) (wasm://wasm/Vosklet.wasm-01f04bca:wasm-function[410]:0x157d4)
    at Vosklet.wasm.void std::__2::__invoke_void_return_wrapper<void, true>::__call[abi:ne180100]<genericModel::extractAndLoad(int, int)::$_0&>(genericModel::extractAndLoad(int, int)::$_0&) (wasm://wasm/Vosklet.wasm-01f04bca:wasm-function[408]:0x15787)
```

but pointer to the tar is correct, I compared memory view with offline hex viewer
![image](https://github.com/msqr1/Vosklet/assets/3808833/5b45d520-5aea-48fa-9ce1-6adca3643a45)

**Comment by korabelnikov** [comment]
According to assmebly, it fails at std::string::substr, so I think, it's here

![image](https://github.com/msqr1/Vosklet/assets/3808833/8acdd0dd-98ed-49f4-a366-2fa459be70a6)

**Comment by korabelnikov** [comment]
I managed out, I repacked tarball given by vosk-browser (I removed top-level hidden file, and all the hidden files there).

**Comment by msqr1** [comment]
So the issue was that model files wasn't tgz'ed in the top-level directory, right?

**Comment by korabelnikov** [comment]
not exact, the issue was in that, you have a line in code which assume that all the files in tarball have '/' in their path, and then you strip the dirname. But tarball from vosk-browser contains some hidden files at top level.
attempting to find '/' returns -1
then substring(0, -1) crashes the program

**Comment by msqr1** [comment]
Alr imma fix this! Thanks for your help!

**Comment by msqr1** [comment]
It took a long time, but it seemed that I fix mine. Could you recheck so I can close the issue?

**Comment by twihorses** [comment]
hola , me parece genial este codigo, solo quisiera me indicaras como crear el Vosklet.js para Español . https://ccoreilly.github.io/vosk-browser/models/vosk-model-small-es-0.3.tar.gz ,  me gustaria poder contribuir audando de alguna manera.  gracias

**Comment by msqr1** [comment]
Hi, sorry, I had to use Google Translate. Anyways, you can copy the code from the top-level README into a html file, then swap the English model out for the Spanish one and it should just work. You can check devtool network, console to verify that the model is being fetched and loaded.
